title: AlfyGamePLAY
description: Nèèèè
theme: just-the-docs
color_scheme: dark
favicon_ico: "/assets/images/logo.ico"

search_enabled: true

search:
  previews: 3
  rel_url: false
  
heading_anchors: true

url: https://alfygame.github.io/


nav_external_links:
  - title: YouTube
    url: https://www.youtube.com/@AlfyGamePLAY/
    hide_icon: false
    opens_in_new_tab: true


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
