title: AlfyGamePLAY
description: Nèèèè
theme: just-the-docs
color_scheme: dark

search_enabled: true

search:
  previews: 5
  rel_url: false
  
heading_anchors: true

url: https://alfygame.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
