title: AGP Test
description: Sto tostando questa cosa
theme: just-the-docs
color_scheme: dark
search.rel_url: false

url: https://alfygame.github.io/agptest/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
