title: AlfyGamePLAY
description: Nèèèè
theme: just-the-docs
color_scheme: dark
search.rel_url: false

url: https://alfygame.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
